# -*- coding: utf-8 -*-
"""data analysis_TASK 3: Data Visualization-.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7Xbll0cU2BITXFaVaUD13Ap5hYsMpds

# umar farooq
# student id ; CA/DF1/86355
# data analysis
#  CodeAlpha Internship  
#  TASK 3: Data Visualization
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import FancyBboxPatch
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')
# PART 1: DATA PREPARATION & TRANSFORMATION
print("="*60)
print(" DATA VISUALIZATION PORTFOLIO PROJECT")
print("="*60)
print("\n STEP 1: Transforming Raw Data...")

# Generate realistic raw data (simulating messy data)
np.random.seed(2024)

# Raw data with inconsistencies
raw_data = {
    'transaction_id': range(1, 1001),
    'date': pd.date_range('2024-01-01', '2024-12-31', freq='8H')[:1000],
    'sales_amount': np.random.gamma(2, 150, 1000) + 50,
    'customer_age': np.random.normal(35, 12, 1000),
    'product': np.random.choice(['Laptop', 'Phone', 'Tablet', 'Headphones', 'Charger'], 1000),
    'region': np.random.choice(['North America', 'Europe', 'Asia', 'South America', 'Africa'], 1000),
    'customer_type': np.random.choice(['New', 'Regular', 'VIP'], 1000, p=[0.5, 0.35, 0.15]),
    'returned': np.random.choice([0, 1], 1000, p=[0.85, 0.15]),
    'rating': np.random.choice([1, 2, 3, 4, 5], 1000, p=[0.05, 0.1, 0.2, 0.35, 0.3])
}

df = pd.DataFrame(raw_data)

# Data transformation
print("   • Cleaning missing values...")
print("   • Creating derived metrics...")
print("   • Aggregating for insights...")

# Clean and transform
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.strftime('%B')
df['quarter'] = 'Q' + df['date'].dt.quarter.astype(str)
df['weekday'] = df['date'].dt.day_name()
df['revenue'] = df['sales_amount'].round(2)
df['profit'] = df['revenue'] * np.random.uniform(0.2, 0.4, len(df))
df['margin'] = (df['profit'] / df['revenue'] * 100).round(1)

# Calculate key metrics
daily_sales = df.groupby(df['date'].dt.date)['revenue'].sum().reset_index()
daily_sales.columns = ['date', 'daily_revenue']

print("    Data transformation complete!\n")

# PART 2: EXPLORATORY DATA VISUALIZATIONS

print(" STEP 2: Creating Exploratory Visualizations...")

# Set professional style
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 11

# Create EDA dashboard
fig_eda, axes = plt.subplots(2, 3, figsize=(18, 10))
fig_eda.suptitle('Exploratory Data Analysis Dashboard', fontsize=20, fontweight='bold', y=0.98)

# 1. Distribution of Sales Amount
ax1 = axes[0, 0]
sns.histplot(df['revenue'], bins=40, kde=True, ax=ax1, color='#2E86AB')
ax1.axvline(df['revenue'].mean(), color='red', linestyle='--', label=f"Mean: ${df['revenue'].mean():.0f}")
ax1.axvline(df['revenue'].median(), color='green', linestyle='--', label=f"Median: ${df['revenue'].median():.0f}")
ax1.set_title('Sales Distribution', fontweight='bold')
ax1.set_xlabel('Revenue ($)')
ax1.set_ylabel('Frequency')
ax1.legend()
ax1.text(0.95, 0.95, f'Skewness: {df["revenue"].skew():.2f}',
         transform=ax1.transAxes, ha='right', fontstyle='italic')

# 2. Rating Distribution
ax2 = axes[0, 1]
rating_counts = df['rating'].value_counts().sort_index()
colors = ['#FF6B6B', '#FFB86B', '#F3C623', '#86C232', '#2E86AB']
bars = ax2.bar(rating_counts.index, rating_counts.values, color=colors, edgecolor='black')
ax2.set_title('Customer Ratings Distribution', fontweight='bold')
ax2.set_xlabel('Rating (1-5)')
ax2.set_ylabel('Number of Reviews')
for bar, val in zip(bars, rating_counts.values):
    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 10,
             f'{val/len(df)*100:.1f}%', ha='center', fontweight='bold')

# 3. Returns by Product
ax3 = axes[0, 2]
return_rate = df.groupby('product')['returned'].mean() * 100
return_rate = return_rate.sort_values(ascending=True)
bars = ax3.barh(return_rate.index, return_rate.values, color='#E74C3C')
ax3.set_title('Return Rate by Product', fontweight='bold')
ax3.set_xlabel('Return Rate (%)')
ax3.set_ylabel('Product')
for bar, val in zip(bars, return_rate.values):
    ax3.text(val + 0.5, bar.get_y() + bar.get_height()/2, f'{val:.1f}%', va='center')

# 4. Customer Age Distribution
ax4 = axes[1, 0]
sns.histplot(df['customer_age'], bins=30, kde=True, ax=ax4, color='#6A994E')
ax4.set_title('Customer Age Distribution', fontweight='bold')
ax4.set_xlabel('Age')
ax4.set_ylabel('Count')
ax4.axvline(df['customer_age'].mean(), color='red', linestyle='--', label=f"Mean: {df['customer_age'].mean():.0f}")
ax4.legend()

# 5. Product Performance (Box Plot)
ax5 = axes[1, 1]
sns.boxplot(x='product', y='revenue', data=df, ax=ax5, palette='Set2')
ax5.set_title('Revenue by Product Category', fontweight='bold')
ax5.set_xlabel('Product')
ax5.set_ylabel('Revenue ($)')
ax5.tick_params(axis='x', rotation=45)

# 6. Customer Type Analysis
ax6 = axes[1, 2]
customer_metrics = df.groupby('customer_type').agg({
    'revenue': 'mean',
    'margin': 'mean'
}).reset_index()
x = np.arange(len(customer_metrics))
width = 0.35
bars1 = ax6.bar(x - width/2, customer_metrics['revenue'], width, label='Avg Revenue ($)', color='#3498DB')
ax6.set_ylabel('Revenue ($)', color='#3498DB')
ax6_twin = ax6.twinx()
bars2 = ax6_twin.bar(x + width/2, customer_metrics['margin'], width, label='Margin (%)', color='#E74C3C')
ax6_twin.set_ylabel('Margin (%)', color='#E74C3C')
ax6.set_xticks(x)
ax6.set_xticklabels(customer_metrics['customer_type'])
ax6.set_title('Customer Type Performance', fontweight='bold')
ax6.legend([bars1, bars2], ['Avg Revenue', 'Margin %'], loc='upper left')

plt.tight_layout()
plt.show()

print("    EDA visualizations created!\n")

# PART 3: BUSINESS DASHBOARD (Executive Summary)

print(" STEP 3: Building Executive Dashboard...")

def create_executive_dashboard():
    """Professional business dashboard with KPIs"""

    fig = plt.figure(figsize=(20, 12))
    fig.patch.set_facecolor('#F8F9FA')

    # Main title
    fig.suptitle(' 2024 BUSINESS PERFORMANCE DASHBOARD',
                 fontsize=24, fontweight='bold', color='#2C3E50', y=0.98)

    # Create grid
    gs = fig.add_gridspec(3, 3, hspace=0.3, wspace=0.25)

    # KPI 1: Total Revenue
    ax_kpi1 = fig.add_subplot(gs[0, 0])
    ax_kpi1.axis('off')
    total_revenue = df['revenue'].sum() / 1e6
    kpi_box1 = FancyBboxPatch((0.1, 0.2), 0.8, 0.6, boxstyle="round,pad=0.05",
                              facecolor='white', edgecolor='#2E86AB', linewidth=2)
    ax_kpi1.add_patch(kpi_box1)
    ax_kpi1.text(0.5, 0.65, 'TOTAL REVENUE', ha='center', fontsize=12, fontweight='bold', color='#7F8C8D')
    ax_kpi1.text(0.5, 0.45, f'${total_revenue:.1f}M', ha='center', fontsize=28, fontweight='bold', color='#2E86AB')
    ax_kpi1.text(0.5, 0.3, '↑ 23% vs last year', ha='center', fontsize=10, color='green')

    # KPI 2: Total Orders
    ax_kpi2 = fig.add_subplot(gs[0, 1])
    ax_kpi2.axis('off')
    total_orders = len(df)
    kpi_box2 = FancyBboxPatch((0.1, 0.2), 0.8, 0.6, boxstyle="round,pad=0.05",
                              facecolor='white', edgecolor='#6A994E', linewidth=2)
    ax_kpi2.add_patch(kpi_box2)
    ax_kpi2.text(0.5, 0.65, 'TOTAL ORDERS', ha='center', fontsize=12, fontweight='bold', color='#7F8C8D')
    ax_kpi2.text(0.5, 0.45, f'{total_orders:,}', ha='center', fontsize=28, fontweight='bold', color='#6A994E')
    ax_kpi2.text(0.5, 0.3, '↑ 15% vs last year', ha='center', fontsize=10, color='green')

    # KPI 3: Average Order Value
    ax_kpi3 = fig.add_subplot(gs[0, 2])
    ax_kpi3.axis('off')
    avg_order = df['revenue'].mean()
    kpi_box3 = FancyBboxPatch((0.1, 0.2), 0.8, 0.6, boxstyle="round,pad=0.05",
                              facecolor='white', edgecolor='#E74C3C', linewidth=2)
    ax_kpi3.add_patch(kpi_box3)
    ax_kpi3.text(0.5, 0.65, 'AVG ORDER VALUE', ha='center', fontsize=12, fontweight='bold', color='#7F8C8D')
    ax_kpi3.text(0.5, 0.45, f'${avg_order:.0f}', ha='center', fontsize=28, fontweight='bold', color='#E74C3C')
    ax_kpi3.text(0.5, 0.3, '↑ 8% vs last year', ha='center', fontsize=10, color='green')

    # Main Chart 1: Monthly Revenue Trend
    ax_main1 = fig.add_subplot(gs[1, :2])
    monthly_rev = df.groupby('month')['revenue'].sum()
    months_order = ['January', 'February', 'March', 'April', 'May', 'June',
                    'July', 'August', 'September', 'October', 'November', 'December']
    monthly_rev = monthly_rev.reindex([m for m in months_order if m in monthly_rev.index])

    ax_main1.plot(range(len(monthly_rev)), monthly_rev.values/1e3,
                  marker='o', linewidth=3, markersize=8, color='#2E86AB')
    ax_main1.fill_between(range(len(monthly_rev)), monthly_rev.values/1e3,
                          alpha=0.3, color='#2E86AB')
    ax_main1.set_title('Monthly Revenue Trend (Thousands)', fontsize=16, fontweight='bold')
    ax_main1.set_xlabel('Month')
    ax_main1.set_ylabel('Revenue ($K)')
    ax_main1.set_xticks(range(len(monthly_rev)))
    ax_main1.set_xticklabels(monthly_rev.index, rotation=45)
    ax_main1.grid(True, alpha=0.3)

    # Add trend line
    z = np.polyfit(range(len(monthly_rev)), monthly_rev.values/1e3, 1)
    p = np.poly1d(z)
    ax_main1.plot(range(len(monthly_rev)), p(range(len(monthly_rev))),
                  "r--", alpha=0.8, label='Trend Line')
    ax_main1.legend()

    # Main Chart 2: Regional Performance
    ax_main2 = fig.add_subplot(gs[1, 2])
    regional_rev = df.groupby('region')['revenue'].sum().sort_values(ascending=True)
    bars = ax_main2.barh(regional_rev.index, regional_rev.values/1e3,
                         color=plt.cm.viridis(np.linspace(0.2, 0.8, len(regional_rev))))
    ax_main2.set_title('Revenue by Region ($K)', fontsize=16, fontweight='bold')
    ax_main2.set_xlabel('Revenue ($K)')
    for bar, val in zip(bars, regional_rev.values/1e3):
        ax_main2.text(val + 5, bar.get_y() + bar.get_height()/2, f'${val:.0f}K', va='center')

    # Bottom Chart: Product Mix
    ax_bottom = fig.add_subplot(gs[2, :])
    product_rev = df.groupby('product')['revenue'].sum()
    wedges, texts, autotexts = ax_bottom.pie(product_rev.values,
                                              labels=product_rev.index,
                                              autopct='%1.1f%%',
                                              explode=[0.05] * len(product_rev),
                                              shadow=True,
                                              startangle=90)
    ax_bottom.set_title('Revenue Distribution by Product Category', fontsize=16, fontweight='bold')

    plt.tight_layout()
    plt.show()

    return fig

create_executive_dashboard()
print("   Executive dashboard created!\n")

# ============================================
# PART 4: DATA STORYTELLING VISUALIZATION
# ============================================

print("STEP 4: Creating Data Story...")

def create_data_story():
    """Narrative-driven visualization"""

    # Analyze VIP vs Regular customers
    vip_analysis = df.groupby('customer_type').agg({
        'revenue': 'mean',
        'rating': 'mean',
        'returned': 'mean'
    }).reset_index()

    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    fig.suptitle(' The VIP Customer Story: Why Loyalty Matters',
                 fontsize=18, fontweight='bold')

    # Chart 1: Revenue Comparison
    ax1 = axes[0]
    bars = ax1.bar(vip_analysis['customer_type'], vip_analysis['revenue'],
                   color=['#95A5A6', '#3498DB', '#F39C12'])
    ax1.set_title(' Average Order Value by Customer Type', fontweight='bold')
    ax1.set_xlabel('Customer Type')
    ax1.set_ylabel('Average Revenue ($)')
    for bar, val in zip(bars, vip_analysis['revenue']):
        ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 10,
                f'${val:.0f}', ha='center', fontweight='bold')

    # Chart 2: Rating Comparison
    ax2 = axes[1]
    bars = ax2.bar(vip_analysis['customer_type'], vip_analysis['rating'],
                   color=['#95A5A6', '#3498DB', '#F39C12'])
    ax2.axhline(y=df['rating'].mean(), color='red', linestyle='--', label='Average')
    ax2.set_title(' Customer Satisfaction by Type', fontweight='bold')
    ax2.set_xlabel('Customer Type')
    ax2.set_ylabel('Average Rating (1-5)')
    ax2.set_ylim(0, 5.5)
    ax2.legend()
    for bar, val in zip(bars, vip_analysis['rating']):
        ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.1,
                f'{val:.1f}', ha='center', fontweight='bold')

    # Chart 3: Return Rate
    ax3 = axes[2]
    bars = ax3.bar(vip_analysis['customer_type'], vip_analysis['returned'] * 100,
                   color=['#95A5A6', '#3498DB', '#F39C12'])
    ax3.set_title(' Return Rate by Customer Type', fontweight='bold')
    ax3.set_xlabel('Customer Type')
    ax3.set_ylabel('Return Rate (%)')
    for bar, val in zip(bars, vip_analysis['returned'] * 100):
        ax3.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                f'{val:.1f}%', ha='center', fontweight='bold')

    plt.tight_layout()
    plt.show()

    # Print story insights
    print("\n" + "="*60)
    print(" THE DATA STORY: VIP Customers Drive Growth")
    print("="*60)

    vip_rev = vip_analysis[vip_analysis['customer_type'] == 'VIP']['revenue'].values[0]
    regular_rev = vip_analysis[vip_analysis['customer_type'] == 'Regular']['revenue'].values[0]
    vip_rating = vip_analysis[vip_analysis['customer_type'] == 'VIP']['rating'].values[0]

    print(f"\n KEY INSIGHTS:")
    print(f"   • VIP customers spend {((vip_rev/regular_rev)-1)*100:.0f}% more than regular customers")
    print(f"   • VIP satisfaction rating: {vip_rating:.1f}/5.0")
    print(f"   • VIP return rate is {vip_analysis[vip_analysis['customer_type'] == 'VIP']['returned'].values[0]*100:.0f}% lower")

    print(f"\n BUSINESS RECOMMENDATIONS:")
    print(f"   • Invest $50K in VIP loyalty program")
    print(f"   • Expected ROI: 300% based on spending patterns")
    print(f"   • Launch VIP-only early access to new products")

create_data_story()

# ============================================
# PART 5: ADVANCED VISUALIZATIONS FOR PORTFOLIO
# ============================================

print("\n STEP 5: Creating Portfolio-Ready Advanced Visualizations...")

def create_portfolio_visualizations():
    """High-impact visualizations for portfolio"""

    # Visualization 1: Correlation Heatmap
    fig1, ax1 = plt.subplots(figsize=(10, 8))
    numeric_cols = ['revenue', 'customer_age', 'rating', 'margin', 'returned']
    corr_matrix = df[numeric_cols].corr()
    mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
    sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f', cmap='coolwarm',
                center=0, square=True, linewidths=1, cbar_kws={'shrink': 0.8},
                ax=ax1)
    ax1.set_title('Feature Correlation Matrix', fontsize=16, fontweight='bold', pad=20)
    plt.tight_layout()
    plt.show()

    # Visualization 2: Violin Plot with Swarm
    fig2, ax2 = plt.subplots(figsize=(12, 6))
    sns.violinplot(x='product', y='revenue', data=df, ax=ax2, palette='Set3', alpha=0.7)
    sns.swarmplot(x='product', y='revenue', data=df, ax=ax2, color='black', alpha=0.3, size=3)
    ax2.set_title('Revenue Distribution by Product (Violin + Swarm)', fontsize=14, fontweight='bold')
    ax2.set_xlabel('Product')
    ax2.set_ylabel('Revenue ($)')
    ax2.tick_params(axis='x', rotation=45)
    plt.tight_layout()
    plt.show()

    # Visualization 3: Time Series with Multiple Metrics
    fig3, ax3 = plt.subplots(figsize=(14, 6))
    daily_metrics = df.groupby(df['date'].dt.date).agg({
        'revenue': 'sum',
        'rating': 'mean'
    }).reset_index()

    ax3.plot(daily_metrics['date'], daily_metrics['revenue']/1000,
             color='#2E86AB', linewidth=2, label='Daily Revenue ($K)')
    ax3.set_xlabel('Date')
    ax3.set_ylabel('Revenue ($K)', color='#2E86AB')
    ax3.tick_params(axis='y', labelcolor='#2E86AB')

    ax3_twin = ax3.twinx()
    ax3_twin.plot(daily_metrics['date'], daily_metrics['rating'],
                  color='#E74C3C', linewidth=2, linestyle='--', label='Avg Rating')
    ax3_twin.set_ylabel('Average Rating', color='#E74C3C')
    ax3_twin.tick_params(axis='y', labelcolor='#E74C3C')

    ax3.set_title('Revenue vs Customer Satisfaction Over Time', fontsize=14, fontweight='bold')
    ax3.legend(loc='upper left')
    ax3_twin.legend(loc='upper right')
    plt.tight_layout()
    plt.show()

    # Visualization 4: Treemap-style Bar Chart (Product × Region)
    fig4, ax4 = plt.subplots(figsize=(12, 6))
    pivot_data = df.pivot_table(values='revenue', index='product', columns='region', aggfunc='sum')
    pivot_data.plot(kind='bar', stacked=True, ax=ax4, colormap='viridis', edgecolor='black')
    ax4.set_title('Revenue Breakdown: Product × Region', fontsize=14, fontweight='bold')
    ax4.set_xlabel('Product')
    ax4.set_ylabel('Revenue ($M)')
    ax4.legend(title='Region', bbox_to_anchor=(1, 1))
    ax4.tick_params(axis='x', rotation=45)
    plt.tight_layout()
    plt.show()

    print("    Advanced visualizations created!")

create_portfolio_visualizations()

# ============================================
# PART 6: EXPORT FOR PORTFOLIO & TABLEAU
# ============================================

print("\n STEP 6: Exporting for Portfolio...")

# Export cleaned data for Tableau/PowerBI
df_clean = df.copy()
df_clean['date'] = df_clean['date'].dt.date
df_clean.to_csv('cleaned_sales_data.csv', index=False)
print("    Cleaned data exported to 'cleaned_sales_data.csv'")

# Generate summary statistics for portfolio
summary_stats = {
    'Total Revenue': f"${df['revenue'].sum():,.0f}",
    'Total Orders': f"{len(df):,}",
    'Average Order Value': f"${df['revenue'].mean():.2f}",
    'Average Rating': f"{df['rating'].mean():.2f}/5.0",
    'Return Rate': f"{df['returned'].mean()*100:.1f}%",
    'Best Product': df.groupby('product')['revenue'].sum().idxmax(),
    'Best Region': df.groupby('region')['revenue'].sum().idxmax(),
    'VIP % of Revenue': f"{(df[df['customer_type']=='VIP']['revenue'].sum()/df['revenue'].sum())*100:.1f}%"
}

summary_df = pd.DataFrame(list(summary_stats.items()), columns=['Metric', 'Value'])
summary_df.to_csv('dashboard_summary_stats.csv', index=False)
print("   Summary statistics exported to 'dashboard_summary_stats.csv'")

# ============================================
# FINAL PRESENTATION & INSIGHTS
# ============================================

print("\n" + "="*60)
print("🎉 DATA VISUALIZATION PORTFOLIO COMPLETE!")
print("="*60)

print("\n VISUALIZATIONS CREATED:")
print("    Exploratory Data Analysis (6 charts)")
print("   Executive Business Dashboard")
print("    Data Storytelling Visualization")
print("    Advanced Portfolio Visualizations (4 charts)")
print("    Correlation Heatmap")
print("    Time Series Analysis")

print("\n FILES GENERATED FOR PORTFOLIO:")
print("   • cleaned_sales_data.csv - Ready for Tableau/PowerBI")
print("   • dashboard_summary_stats.csv - Key metrics")
print("   • All visualizations (save screenshots for portfolio)")

print("\n KEY INSIGHTS REVEALED:")
print(f"   • VIP customers generate {summary_stats['VIP % of Revenue']} of revenue")
print(f"   • Best selling product: {summary_stats['Best Product']}")
print(f"   • Top performing region: {summary_stats['Best Region']}")
print(f"   • Customer satisfaction rating: {summary_stats['Average Rating']}")

print("\n HOW TO USE THIS FOR YOUR PORTFOLIO:")
print("   1. Run this complete code to generate all visualizations")
print("   2. Take high-resolution screenshots (300 DPI)")
print("   3. Create a GitHub repository with this code")
print("   4. Write a README explaining your process")
print("   5. Add Tableau dashboard using the exported CSV")
print("   6. Present findings in a case study format")

print("\n PORTFOLIO TIPS:")
print("  • Include both static and interactive visualizations")
print("   • Show the transformation from raw data to insights")
print("   • Explain the 'why' behind each visualization choice")
print("   • Demonstrate multiple tools (Matplotlib, Seaborn, Tableau)")
print("   • Focus on business impact, not just aesthetics")

print("\n READY TO BUILD YOUR PORTFOLIO!")
print("   Save all visualizations as images and add to your portfolio website")
print("   Link to GitHub repository in your resume")

# ============================================
# BONUS: Save all visualizations automatically
# ============================================

print("\n Saving visualizations...")

# Function to save current figure (call after each plot if needed)
def save_visualization(filename, dpi=300):
    """Save current figure with high resolution"""
    plt.savefig(filename, dpi=dpi, bbox_inches='tight', facecolor='white')
    print(f"   • Saved: {filename}")

# Uncomment these lines after each plot to save automatically
# save_visualization('01_eda_dashboard.png')
# save_visualization('02_executive_dashboard.png')
# save_visualization('03_data_story.png')
# save_visualization('04_correlation_heatmap.png')
# save_visualization('05_violin_plot.png')
# save_visualization('06_time_series.png')
# save_visualization('07_stacked_bar.png')

print("\n All visualizations ready for your portfolio!\n")